### ISSUE TITLE
Live Segment and Perf Predictor does not work on Firefox Linux

### ISSUE THREAD

**Issue by lcarcamo1526** [SauceLLC/sauce4strava#131]
Greeting, 
First thank you for this incredible extension.
I would like to report a bug on Firefox running on Arch Linux
when i try to download a live segment or see the Perf predictor this button don't trigger any action, I've tried in Chromium and it works well, I've my account linked with Patron, here is my user agent if you needed:

```
Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0
Other HTTP headers
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
```

**Comment by mayfield** [comment]
Hi @lcarcamo1526 they are both working on my firefox 103.0.1 machine.  Can you hit F12, reload the page and try it again, then report any logs in the Console tab?

**Comment by mayfield** [comment]
Oh and can you send me the activity you are testing with?  It could be specific to that one/type.

**Comment by lcarcamo1526** [comment]
It happen in all the activities, included mines.

Those are the console logs, when i enter in the an activity website, after click the buttons I'm not getting any warning.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://c.strava.com/com.snowplowanalytics.snowplow/tp2. (Reason: CORS request did not succeed). Status code: (null).
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. 2992978873869372496
Sauce loading: Analysis boot.js:397:25
loading global libraries globalLibraries.js:26:8
Branch Web SDK is being shimmed by Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1716220 for details. sandbox eval code:1:9
Facebook SDK is being shimmed by Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1226498 for details. shim_messaging_helper.js:23:15
Warning! Requiring the `autotrack` plugin no longer requires  all sub-plugins by default.
See https://goo.gl/XsXPg5 for details. instrument.js:107:32
TypeError: window.branch[fn] is undefined
    push https://cdn.branch.io/branch-latest.min.js:75
    <anonymous> https://cdn.branch.io/branch-latest.min.js:80
instrument.js:107:32
Sauce inteceptCallback failed (falling back to ajax): DOMException: A mutation operation was attempted on a database that did not allow mutations. instrument.js:107:32
    p instrument.js:107
    ajax 2992978873869372496:2088
    (Async: promise callback)
    ajax 2992978873869372496:2086
    sync application-1f29486af479f2fb744694df43993b8d8ce62db650cd5594af266dadf156d90c.js:6
    sync application-1f29486af479f2fb744694df43993b8d8ce62db650cd5594af266dadf156d90c.js:6
    fetch application-1f29486af479f2fb744694df43993b8d8ce62db650cd5594af266dadf156d90c.js:6
    interceptModelFetch 2992978873869372496:2096
    fetchRemote ride_manifest-7f9611b6a05fe5df0aa1fdd35e8336baa2c82ce9395a02be540a8299f1f20004.js:4
    fetchStreams ride_manifest-7f9611b6a05fe5df0aa1fdd35e8336baa2c82ce9395a02be540a8299f1f20004.js:4
    request ride_manifest-7f9611b6a05fe5df0aa1fdd35e8336baa2c82ce9395a02be540a8299f1f20004.js:4
    initializeMap ride_manifest-7f9611b6a05fe5df0aa1fdd35e8336baa2c82ce9395a02be540a8299f1f20004.js:18
    assemble ride_manifest-7f9611b6a05fe5df0aa1fdd35e8336baa2c82ce9395a02be540a8299f1f20004.js:18
    assemble ride_manifest-7f9611b6a05fe5df0aa1fdd35e8336baa2c82ce9395a02be540a8299f1f20004.js:19
    assemble 2992978873869372496:1422
    <anonymous> 2992978873869372496:3258
Sauce inteceptCallback failed (falling back to ajax): DOMException: A mutation operation was attempted on a database that did not allow mutations. instrument.js:107:32
    p instrument.js:107
    ajax 2992978873869372496:2088
    (Async: promise callback)
    ajax 2992978873869372496:2086
    sync application-1f29486af479f2fb744694df43993b8d8ce62db650cd5594af266dadf156d90c.js:6
    sync application-1f29486af479f2fb744694df43993b8d8ce62db650cd5594af266dadf156d90c.js:6
    fetch application-1f29486af479f2fb744694df43993b8d8ce62db650cd5594af266dadf156d90c.js:6
    interceptModelFetch 2992978873869372496:2096
    fetchRemote ride_manifest-7f9611b6a05fe5df0aa1fdd35e8336baa2c82ce9395a02be540a8299f1f20004.js:4
    fetchStreams ride_manifest-7f9611b6a05fe5df0aa1fdd35e8336baa2c82ce9395a02be540a8299f1f20004.js:4
    request ride_manifest-7f9611b6a05fe5df0aa1fdd35e8336baa2c82ce9395a02be540a8299f1f20004.js:4
    PageView ride_manifest-7f9611b6a05fe5df0aa1fdd35e8336baa2c82ce9395a02be540a8299f1f20004.js:18
    a application-1f29486af479f2fb744694df43993b8d8ce62db650cd5594af266dadf156d90c.js:6
    trigger application-1f29486af479f2fb744694df43993b8d8ce62db650cd5594af266dadf156d90c.js:6
    route application-1f29486af479f2fb744694df43993b8d8ce62db650cd5594af266dadf156d90c.js:6
    loadUrl application-1f29486af479f2fb744694df43993b8d8ce62db650cd5594af266dadf156d90c.js:6
    any application-1f29486af479f2fb744694df43993b8d8ce62db650cd5594af266dadf156d90c.js:5
    loadUrl application-1f29486af479f2fb744694df43993b8d8ce62db650cd5594af266dadf156d90c.js:6
    start application-1f29486af479f2fb744694df43993b8d8ce62db650cd5594af266dadf156d90c.js:6
    <anonymous> 2992978873869372496:3483
    i 16971-5329dde5fa00d9937cee.js line 1 > eval:2
    fireWith 16971-5329dde5fa00d9937cee.js line 1 > eval:2
    ready 16971-5329dde5fa00d9937cee.js line 1 > eval:2
    J 16971-5329dde5fa00d9937cee.js line 1 > eval:2
    (Async: EventListener.handleEvent)
    promise 16971-5329dde5fa00d9937cee.js line 1 > eval:2
    <anonymous> 16971-5329dde5fa00d9937cee.js line 1 > eval:2
    <anonymous> 16971-5329dde5fa00d9937cee.js line 1 > eval:2
    <anonymous> 16971-5329dde5fa00d9937cee.js line 1 > eval:2
    exports addScript.js:20
    10603 jQuery
    Webpack 10
Relative positioning of table rows and row groups is now supported. This site may need to be updated because it may depend on this feature having no effect. 2992978873869372496
XHRGEThttps://a.tiles.mapbox.com/v4/mapbox.satellite,mapbox.mapbox-terrain-dem-v1,mapbox.mapbox-streets-v8.json?access_token=pk.eyJ1Ijoic3RyYXZhIiwiYSI6IlpoeXU2U0UifQ.c7yhlZevNRFCqHYm6G6Cyg&secure
[HTTP/1.1 400 Bad Request 174ms]

Sauce Error: Error: A mutation operation was attempted on a database that did not allow mutations.
    reportError moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/common/base.js:1293
    refreshLoop moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/bg/hist.mjs:1959
    fn moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/site/proxy.js:123
    initSyncActivity moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/site/analysis.js:3242
    prepare moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/site/analysis.js:3297
    load moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/site/analysis.js:3578
    async* moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/site/analysis.js:3829
    <anonymous> moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/site/analysis.js:3835
instrument.js:107:32
Uncaught (in promise) Error: A mutation operation was attempted on a database that did not allow mutations.
    reportError moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/common/base.js:1293
    refreshLoop moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/bg/hist.mjs:1959
    fn moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/site/proxy.js:123
    initSyncActivity moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/site/analysis.js:3242
    prepare moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/site/analysis.js:3297
    load moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/site/analysis.js:3578
    async* moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/site/analysis.js:3829
    <anonymous> moz-extension://d74fea03-989b-4121-b970-869d2befca7c/src/site/analysis.js:3835
proxy.js:220:27
could not load TileJSON at mapbox://styles/strava/ckzn9habn001i15qtww7535k9 instrument.js:107:32
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o352714.ingest.sentry.io/api/5816222/envelope/?sentry_key=6ffc1c27d92347b49d7659886aab9deb&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.10.0. (Reason: CORS request did not succeed). Status code: (null).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://c.strava.com/com.snowplowanalytics.snowplow/tp2. (Reason: CORS request did not succeed). Status code: (null).
Sauce inteceptCallback failed (falling back to ajax): DOMException: A mutation operation was attempted on a database that did not allow mutations. instrument.js:107:32
Sauce inteceptCallback failed (falling back to ajax): DOMException: A mutation operation was attempted on a database that did not allow mutations. instrument.js:107:32
Sauce inteceptCallback failed (falling back to ajax): DOMException: A mutation operation was attempted on a database that did not allow mutations. instrument.js:107:32
Sauce inteceptCallback failed (falling back to ajax): DOMException: A mutation operation was attempted on a database that did not allow mutations. instrument.js:107:32
XHRGEThttps://a.tiles.mapbox.com/v4/mapbox.satellite,mapbox.mapbox-terrain-dem-v1,mapbox.mapbox-streets-v8.json?access_token=pk.eyJ1Ijoic3RyYXZhIiwiYSI6IlpoeXU2U0UifQ.c7yhlZevNRFCqHYm6G6Cyg&secure
[HTTP/1.1 400 Bad Request 45ms]

could not load TileJSON at mapbox://styles/strava/ckzn9habn001i15qtww7535k9 instrument.js:107:32
Uncaught (in promise) DOMException: A mutation operation was attempted on a database that did not allow mutations. 2992978873869372496:1176:51
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o352714.ingest.sentry.io/api/5816222/envelope/?sentry_key=6ffc1c27d92347b49d7659886aab9deb&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.10.0. (Reason: CORS request did not succeed). Status code: (null).
Uncaught (in promise) DOMException: A mutation operation was attempted on a database that did not allow mutations. 2992978873869372496:1176:51
Uncaught (in promise) DOMException: A mutation operation was attempted on a database that did not allow mutations. 2992978873869372496:1176:51
Uncaught (in promise) DOMException: A mutation operation was attempted on a database that did not allow mutations. 2992978873869372496:1176:51

```

**Comment by mayfield** [comment]
Looks like incognito mode maybe?  The indexedb calls are failing which firefox disables for incognito.  That or perhaps another extension that attempts to block that?

**Comment by lcarcamo1526** [comment]
@mayfield this was the [original activity ](https://www.strava.com/activities/7623351321)

**Comment by lcarcamo1526** [comment]
> Looks like incognito mode maybe? The indexedb calls are failing which firefox disables for incognito. That or perhaps another extension that attempts to block that?

Makes sense, Firefox has enable Enhanced Tracking Protection on Strict and "Do not track" is on.
I'm also using Ublock Origin

**Comment by mayfield** [comment]
Last I checked those settings should be fine as long as you're not using incognito.  Let me check again.

**Comment by mayfield** [comment]
Yeah, I actually have my firefox setup the same way;  ublock and strict ETP.  Any other extensions that might be interfering?  Or perhaps out of disk space?

**Comment by lcarcamo1526** [comment]
> Last I checked those settings should be fine as long as you're not using incognito. Let me check again.

You're right, I was not in Incognito but Firefox has custom settings to not save history, i enabled that option and it worked again!

Thank you for incredible support!

**Comment by mayfield** [comment]
Oh good, glad we figured it out!

Cheers!
